@startuml
class BP_Block {
    -BeginPlay()
    -OnComponentBeginOverlap()
    +DoSpawnObstacles : Boolean
    +CheckFrontBlock() : BP_Block
    +MoveCars()
    +SpawnObstacles()
} 

class BP_ThirdPersonGameMode {
    -BeginPlay()
    +AddBlock(DoSpawnObstacles : Boolean)
}

class BP_ThirdPersonCharacter {
    -BeginPlay()
}


Object <|-- Actor
Actor  <|-- GameModeBase
Character <|-- BP_ThirdPersonCharacter
Pawn <|-- Character
Actor  <|-- Pawn
Actor  <|-- BP_Block
GameModeBase <|-- BP_ThirdPersonGameMode
BP_ThirdPersonGameMode--BP_Block : > spawns from class
@enduml
