@startuml
class BP_Block {
    -BeginPlay()
    -OnComponentBeginOverlap()
    +DoSpawnObstacles : Boolean
    +CheckFrontBlock() : BP_Block
    +MoveCars()
    +SpawnObstacles()
} 

class BP_ThirdPersonGameMode {
    -BeginPlay()
    +AddBlock(DoSpawnObstacles : Boolean)
}

class BP_ThirdPersonCharacter {
    -BeginPlay()
}


Object <|-- Actor
Actor  <|-- GameModeBase
Actor  <|-- BP_ThirdPersonCharacter
Actor  <|-- BP_Block
GameModeBase <|-- BP_ThirdPersonGameMode
@enduml
